### ISSUE TITLE
Change link of cubevizjs.min.js to master branch version of the file on Github

### ISSUE THREAD

**Issue by k00ni** [AKSW/cubevizjs#10]
Path will be: https://github.com/AKSW/cubevizjs/tree/master/dist/cubevizjs.min.js

@GeorgesAlkhouri: He will merge and provide the final min.js file

**Comment by GeorgesAlkhouri** [comment]
Done. 

Versioned cubeviz.min.js will be provided under:

https://raw.githubusercontent.com/AKSW/cubevizjs/master/dist/cubeviz.min.js

@simeonackermann, could you change the demo sites CubeViz integration to point to the above link?

Feel free to close issue when done.

**Comment by simeonackermann** [comment]
Thanks, applied to demo site and jsfiddles.

**Comment by k00ni** [comment]
Can this issue be closed?

**Comment by GeorgesAlkhouri** [comment]
@simeonackermann, CubeViz needs to be linked against this link:

https://raw.githubusercontent.com/AKSW/cubevizjs/master/dist/cubeviz.min.js

But currently points to the following:

http://cdn.rawgit.com/AKSW/cubevizjs/master/dist/cubeviz.min.js

And therefore can not display the current version of CubeViz.

**Comment by simeonackermann** [comment]
I thought these are the same versions (maybe the cdn is cached), except that the cdn sends the right content type (JS).

**Comment by simeonackermann** [comment]
Ok, it seems the cache is permanently.

**Comment by simeonackermann** [comment]
Alternatively it's recommended to use http://rawgit.com/AKSW/cubevizjs/master/dist/cubeviz.min.js , it's not cached but uses the right content-type and therefore reduces the load and performance.

**Comment by simeonackermann** [comment]
Done. Can be closed.
