### ISSUE TITLE
You are currently using minified code outside [...]

### ISSUE THREAD

**Issue by k00ni** [AKSW/cubevizjs#11]
I got the following output on my console:

> cubeviz.min.js:19 You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.n @ cubeviz.min.js:19
> 
> cubeviz.min.js:28 Either the global navigator was undefined or an invalid userAgent was provided. Using a valid userAgent? Please let us know and create an issue at https://github.com/rofrischmann/inline-style-prefixer/issues

**Comment by k00ni** [comment]
Could please describe in one or two sentences what the problem was and how you fixed it?

**Comment by GeorgesAlkhouri** [comment]
While building CubeViz for production I forgot to tell Redux and other third party tools this fact. So they "complained" about this because I am using a slower development build of them.

**Comment by douzi19970118** [comment]
fuvk
