### ISSUE TITLE
Add readme

### ISSUE THREAD

**Issue by GeorgesAlkhouri** [AKSW/cubevizjs#13]
- [x] Prepare Readme file with help texts
  - [x] test browser support
  - [x] check cross-origin stuff in different flavours (Cors Support)
  - [x] describe usually use cases (e.g. to import, to select,...)
  - [x] which RDF formats are supported
  - [x] describe developer-tools/helpers (e.g. log-box, console, ..)

**Comment by pietercolpaert** [comment]
Please do! And add a project URL to the short description of the repo
