### ISSUE TITLE
Add Travis integration

### ISSUE THREAD

**Issue by k00ni** [AKSW/cubevizjs#15]

**Comment by GeorgesAlkhouri** [comment]
Done

 [![Build Status](https://travis-ci.org/AKSW/cubevizjs.svg?branch=develop)](https://travis-ci.org/AKSW/cubevizjs)

Travis now tests and builds for us. 
But we need to think about deploying. Currently we are pushing the min.js  and source map file to the repositories distribution folder.

Is there a better solution?

**Comment by k00ni** [comment]
What deployment-scenarios do you think exist in our case? Maybe publishing a node.js package too?

**Comment by GeorgesAlkhouri** [comment]
Travis can deploy to github releases, for example. 

But this don't solve the problem of distributing the cubeviz.min.js. 
The point is that if you forget to manually build and commit cubeviz.min.js with or after every commit the repository state and the provided cubeviz.min.js version will differ. Which is really confusing.
