### ISSUE TITLE
Add licence

### ISSUE THREAD

**Issue by GeorgesAlkhouri** [AKSW/cubevizjs#18]
@k00ni, which licence do you recommend? Currently, we do not use any code from eccenca.

**Comment by k00ni** [comment]
I would suggest GPL 3 to force re-publishing of derivative work. What do you think?

**Comment by seebi** [comment]
AFAIK, GPL 3 would disallow any integration in commercial products.
javascript stuff is typically MIT licensed so why not here?

**Comment by k00ni** [comment]
Hi @seebi, good point. We consider CubeViz.js to be used in commercial products too. If @GeorgesAlkhouri has no complains, i would use MIT too.
