### ISSUE TITLE
Prepare for demo paper

### ISSUE THREAD

**Issue by k00ni** [AKSW/cubevizjs#2]
Must have:
- [x] 1. Finish public API (configuration object, run() method for demo integration)
- [x] 2. Minimizing later generated distribution file; cleanup of dependencies
- [x] 3. Rename distribution file to cubeviz.min.js
- [x] 4. Labels in chart view are short and does not overlay each other

Optional:
- [x] 1. If possible, a basic grouping of dimension elements by according dimension

**Comment by GeorgesAlkhouri** [comment]
Example integration:

`CubeViz.default(...)` because of following babel 6's default export behavoir. (https://phabricator.babeljs.io/T2212)

```
var configuration = {
    ui_container: 'react',
};
var cubeViz = new CubeViz.default(configuration);
cubeViz.run();
```

**Comment by GeorgesAlkhouri** [comment]
Completed issue, please close when checked.

**Comment by k00ni** [comment]
:+1:
