### ISSUE TITLE
Rework Demo page and help Simeon to apply the new version

### ISSUE THREAD

**Issue by k00ni** [AKSW/cubevizjs#20]

**Comment by k00ni** [comment]
Ping @simeonackermann

**Comment by simeonackermann** [comment]
Is there a new demo page?  I don't have it...

**Comment by GeorgesAlkhouri** [comment]
Nope, the old demo page doesn't represent the current UI of CubeViz.js. So it's all about a refreshment of the site.

**Comment by simeonackermann** [comment]
Ok, its about the usage description?!

**Comment by k00ni** [comment]
Discussions and progress is documented here: https://github.com/AKSW/cubevizjs/issues/23
