### ISSUE TITLE
Update/fix cubevizjs.demo.aksw.org

### ISSUE THREAD

**Issue by k00ni** [AKSW/cubevizjs#23]
... ongoing topic :) @GeorgesAlkhouri and @simeonackermann, please:

* [x] update cubevizjs.demo.aksw.org to use the latest stable release for Case 1
* [x] adapt boilerplate code on demo page for new parameters etc.
* [x] adapt jsfiddles to use latest stable JS file
* [x] setup the docker and related stuff in a way, that further updates are a breeze (something like a simple docker rebuild and start)
* [x] (optional until end of february, but fix it afterwards!) fix cubeviz.aksw.org (e.g. missing screenshot)

**Comment by k00ni** [comment]
Related to https://github.com/AKSW/cubeviz.ontowiki/issues/201

**Comment by simeonackermann** [comment]
Updated the demo page (wait for restart), boilerplate and jsfiddles.

For further updates we simply can update the HTML in [/demo/](https://github.com/AKSW/CubeVizJs-Demopage/tree/master/demo) and call a `docker restart cubevizjs-demo-aksw` on the server (same for the [projectpage)](https://github.com/AKSW/CubeViz-Projectpage).

**Comment by k00ni** [comment]
@GeorgesAlkhouri: Would you please check the updated demo page and close this issue, if its done?

**Comment by simeonackermann** [comment]
The containers are not updated yet. I asked Norman when he is able to do
that...

Am 23.02.2017 um 15:39 schrieb Konrad Abicht:

**Comment by k00ni** [comment]
I don't want to go on your nerves @splattater, but currently the old version is still running. Can you update it before next Monday 1 pm?

**Comment by k00ni** [comment]
Norman wrote me that he will update the demo page next Monday morning.

**Comment by GeorgesAlkhouri** [comment]
I am on it as soon the new demo site goes online.

**Comment by k00ni** [comment]
It seems we done here, right? All unchecked points from the first post are finished?

**Comment by k00ni** [comment]
@simeonackermann please discuss with @GeorgesAlkhouri why in the latest demo page the old commit is shown (b2a9250).

**Comment by simeonackermann** [comment]
The last build of the used [cubeviz.min.js](https://github.com/AKSW/cubevizjs/blob/develop/dist/cubeviz.min.js) in the demo app was 3 months ago as commit b2a9250.

**Comment by k00ni** [comment]
Does that mean that @GeorgesAlkhouri has to rebuild it? Can we simplify this whole process in the future, because this task is becoming very annoying.

**Comment by simeonackermann** [comment]
If the seven newer commits since b2a9250 are noticeable, yes.
