### ISSUE TITLE
Import 2 RDF files: data and vocab

### ISSUE THREAD

**Issue by simeonackermann** [AKSW/cubevizjs#3]
Most of the Data Cubes I've found are separated into the data (observations) and the vocabulary definition file.

May it's useful to give both as file to the configuration.

**Comment by k00ni** [comment]
I wouldn't. My suggestion would be to copy one file into the other and upload it then or put both in a store and reference its SPARQL endpoint to cubevizjs. What you think @GeorgesAlkhouri ?

**Comment by GeorgesAlkhouri** [comment]
I think this could be a **nice to have feature** in the future. But it is not necessary as we want to handle complete data cubes and don't want to handle 2 separate files or be responsible for the correct structure of the cubes.

**Comment by k00ni** [comment]
This two files approach will not be part of cubevizjs soon. But its a nice feature to think about.
