### ISSUE TITLE
Visualization shows all dimension elements twice

### ISSUE THREAD

**Issue by k00ni** [AKSW/cubevizjs#4]
What did i wrong, that it shows each year twice in the visualization?

![cv-pie-with-menu](https://cloud.githubusercontent.com/assets/381727/15899639/b2e42708-2d9c-11e6-9273-42a8c95c50ec.png)

**Comment by simeonackermann** [comment]
One is for Germany and the other for UK, which seems pre-selected dimensions.

These difference types of dimensions (year/country) should maybe separated in the selection UI. But this could be another issue.

**Comment by GeorgesAlkhouri** [comment]
@k00ni this is due to a bug in the rules for the chart selection and I think it'll be fixed by tomorrow.

@simeonackermann Please see #2 (the optional point)

**Comment by GeorgesAlkhouri** [comment]
Fixed by b9e1f8fef8007dad705383f9b7ab376528677960

For now I implemented a basic very strict set of rules. After first release I'll change this again.

**Comment by simeonackermann** [comment]
The are still issues with observations and multiple unit measures. Example: [serbia.n3](https://github.com/AKSW/cubeviz.ontowiki/blob/master/assets/serbia.n3) does have `MIO_NAT` and `RT_GDP` for each year. Both values currently gets into one graph:
![bildschirmfoto vom 2016-06-13 10-15-00](https://cloud.githubusercontent.com/assets/6428217/16000980/d611ba4a-314f-11e6-8344-c04de70a4f14.png)

For such case a measure selection may would be a solution.
Unfortunately these measures are not described in the dataset and I don't know how often these different unit measures are used in other public cubes (I could't find any others in my cubes) - may it's not that often...

**Comment by simeonackermann** [comment]
Ok, the different unit measures are not used in ONE observation, its two observations, which both describe one year and country with different measures.

Example.:

```
<observation1> <cube:unitMeasure> <ex#MIO_NAT>
<observation1> <cube:value> "12345"
<observation1> <ex:geo> <ex:Geo>
<observation1> <ex:time> <ex:Time2000>
<observation2> <cube:unitMeasure> <ex#RT_GDP>
<observation2> <cube:value> "1"
<observation2> <ex:geo> <ex:Geo>
<observation2> <ex:time> <ex:Time2000>
```

**Comment by GeorgesAlkhouri** [comment]
Unfortunately, at this time CubeViz cannot understand unit measures at all. So this two observation points will be treated as two separate points.

**Comment by k00ni** [comment]
You meant to close this with your commit 629042a right?
