### ISSUE TITLE
Load data from files doesn't work

### ISSUE THREAD

**Issue by orinciog** [AKSW/cubevizjs#6]
Hy.

I like your project a lot and I'm trying to get it work with some samples files, but it seems that I can't load data from files.

My environment is the following:
- Firefox 47.0
- Chrome 51.0.2704
- cubeviz.js : taken from https://github.com/AKSW/cubevizjs/blob/develop/dist/cubeviz.min.js
- index.html: taken from https://github.com/AKSW/cubevizjs/blob/develop/dist/index.html
- sample files: [scoreboard.ttl](https://raw.githubusercontent.com/AKSW/cubeviz.ontowiki/master/assets/scoreboard-part-2-dimensional.ttl) or [serbia.n3](https://raw.githubusercontent.com/AKSW/cubeviz.ontowiki/master/assets/serbia.n3)

The errors are:
- Firefox: too much recursion
  (...pe.insert.call(this,e,null,function(e){t(e)})},QuadIndex.prototype.search=functi...) cubeviz.min.js (line 6, col 13189)
- Chrome: cubeviz.min.js:21 TypeError: Cannot read property 'length' of undefined(…)

You can take a look on the errors [here](http://opendata.cs.pub.ro/~octavian/cube/).

Thank you,

**Comment by k00ni** [comment]
Hi @orinciog,

thanks for your interest! I checked your installation and confirm the error. I tried the serbia.n3 within our [demo-installation](http://cubevizjs.demo.aksw.org) and it worked, so it seems that something is wrong with your setup.

@GeorgesAlkhouri: Can you please look into the errors?

Kinda regards

**Comment by simeonackermann** [comment]
I tried exact the same setup locally and curiously it runs fine. But I had to change the datasource in `bundle.js` to `data_source: { value: "serbia.n3" }` because of XHR...

**Comment by GeorgesAlkhouri** [comment]
@orinciog  currently it is not possible to load files (with file upload or file url) lager than 15 MB with CubeViz unless you use a sparql endpoint url of course. I've added an error when this happens via file url. (b6de79b97a27bc1e5e14c505a6b4cf2508e75c4d)

> Cannot read property 'length' of undefined

On that one: I am still investigating.

**Comment by GeorgesAlkhouri** [comment]
@orinciog could you retry to load the files with the current CubeViz version at https://raw.githubusercontent.com/AKSW/cubevizjs/develop/dist/cubeviz.min.js . 
Please keep in mind that currently `scoreboard.ttl` is to big to get uploaded in CubeViz.js directly, so you have to upload it to a rdf store and input the endpoint url to CubeViz.js.  
For further information please look at the [README](https://github.com/AKSW/cubevizjs/blob/develop/README.md) file

**Comment by k00ni** [comment]
@orinciog: I will close this for now, because our internal tests were successful and no reaction from you since opening the issue. Don't hesitate to comment here if you run into further problems! Thanks for sharing.
