### ISSUE TITLE
File releases

### ISSUE THREAD

**Issue by k00ni** [AKSW/cubevizjs#7]
TODO:
- [x] - File release 0.1 - Reflects the state of the demo for SEMANTICS conference
- [x] - File release 0.2 - Reflects the results of refactoring and consolidation

For each release please write basic features (~ 5 points).

For 0.2 please write about the reasons for the decision to use redux too.

**Comment by GeorgesAlkhouri** [comment]
Released new version of CubeViz (https://github.com/AKSW/cubevizjs/releases/tag/v0.2.0)
