### ISSUE TITLE
Attribute handling

### ISSUE THREAD

**Issue by k00ni** [AKSW/cubevizjs#8]
(is related to #4)

We are currently struggling with the many ways to define an attribute. There are multiple cases how to express attribute information:
### Case 1 (**is supported**)

 attribute is defined in DSD and is used in an observation explicitly 

```
DSD qb:attribute ex:Attribute .
attr1 a ex:Attribute
obs1 ex:Attribute attr1
```

Reference to specification: https://www.w3.org/TR/vocab-data-cube/#dsd-dsd
### Case 2

Attribute is defined using a measurement (implicit):

```
DSD qb:measure ex:Measure .
ex:Measure ??? ex:Attribute . (<=== unclear, research!)
attr1 a ex:Attribute ;
        rdfs:label "kilometer".
obs1 ex:Measure "400"
```

In this `obs1` means that it outlines 400 kilometers.

Reference to specification: https://www.w3.org/TR/vocab-data-cube/#dsd-mm

> Attributes can also be attached directly to the qb:MeasureProperty itself (e.g. to indicate the unit of measure for that measure) but that attachment applies to the whole data set (indeed any data set using that measure property) and cannot vary for different observations.

**Comment by k00ni** [comment]
@GeorgesAlkhouri : please re-check if case 2 solved.

**Comment by GeorgesAlkhouri** [comment]
Nope, unfortunately case 2 is not solved. 

> DSD qb:measure ex:Measure .
> ex:Measure ??? ex:Attribute . (<=== unclear, research!)
> attr1 a ex:Attribute ;
>         rdfs:label "kilometer".
> obs1 ex:Measure "400"

The relation of ex:Measure and ex:Attribute should by qb:attribute, right?

**Comment by k00ni** [comment]
> The relation of ex:Measure and ex:Attribute should by qb:attribute, right?

Yes, you are right.
